[[example]]
name = "hello_world_redis"
path = "examples/hello_world_redis.rs"

[package]
name = "redis_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39", features = ["full"] }
mini-redis = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
bytes = "1"
dashmap = "6.0.1"